sudo: required
addons:
  apt:
    packages:
      - bison
      - git
language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
script:
  - rake clean
  - rake rust
  - rake specinfra
  - rake test
